config/routes.rb
AflierSurvey::Engine.routes.draw do


  devise_for :users, class_name: "User"

  resources :answers do
    member do
      get :choice
      get :option_choice
      get :other
    end
  end

  resources :choice_answers
  resources :option_answers
  resources :questionnaire_submissions
  resources :repeat_sections
  resources :section_progresses

  resources :question_inputs do
    member do
      get :toggle_subtract
    end
  end

  resources :calc_inputs

  resources :belonging_sections do
    member do
      get :up
    end
  end

  resources :options do
    member do
      get :up
    end
  end


  resources :questions do
    resources :options

    member do
      get :up
      get :down
      get :toggle_other
      get :type
      get :result
      get :following
      get :calc
      get :clone
      get :feed
      get :grouping
      get :toggle_input
    end
  end

  resources :calcs do
    member do
      get :var_one
      get :var_two
      get :calc_one
      get :calc_two
      get :operator
      get :choice
      get :question_choice
      get :grouping
    end
  end

  resources :question_sections do
    resources :questions

    member do
      get :report
      get :repeat
      get :complete
      get :include
      get :exclude
    end
  end

  resources :questionnaires do
    member do
      get :submit
      get :assign
      get :save
      get :toggle_input
    end
  end
end

app/models/aflier_survey/application_record.rb
module AflierSurvey
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/aflier_survey/belonging_section.rb
module AflierSurvey
  class BelongingSection < ApplicationRecord
    belongs_to :questionnaire
    belongs_to :question_section
  end
end

app/models/aflier_survey/calc_input.rb
module AflierSurvey
  class CalcInput < ApplicationRecord
  end
end

app/models/aflier_survey/option.rb
module AflierSurvey
  class Option < ApplicationRecord
    belongs_to :question

    has_many :option_mappings
    has_many :option_answers
  end
end

app/models/aflier_survey/option_answer.rb
module AflierSurvey
  class OptionAnswer < ApplicationRecord
    belongs_to :answer
  end
end

app/models/aflier_survey/question_input.rb
module AflierSurvey
  class QuestionInput < ApplicationRecord
    belongs_to :calc
    belongs_to :question
  end
end

app/models/aflier_survey/questionnaire_submission.rb
module AflierSurvey
  class QuestionnaireSubmission < ApplicationRecord
    belongs_to :questionnaire

    validates :unique_ident, presence: true

    SAVED      = 'saved'
    SUBMITTED  = 'submitted'
    UPDATED    = 'updated'
    LOOKING_AT = 'looking_at'
    ASSIGNED   = 'assigned'
  end

end

app/models/aflier_survey/section_progress.rb
module AflierSurvey
  class SectionProgress < ApplicationRecord
    belongs_to :question_section

    COMPLETE = 'complete'.freeze
    UPDATED = 'updated'.freeze
    REQUIRED = 'required'.freeze
  end
end

app/controllers/aflier_survey/answers_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class AnswersController < ApplicationController
    before_action :set_answer, only: [:show, :edit, :update, :destroy, :choice, :option_choice, :other]

    skip_before_action :verify_authenticity_token

    # GET /answers
    # GET /answers.json
    def index
      @answers = Answer.all
    end

    # GET /answers/1
    # GET /answers/1.json
    def show
    end

    # GET /answers/new
    def new
      @answer = Answer.new
    end

    # GET /answers/1/edit
    def edit
    end

    # POST /answers
    # POST /answers.json
    def create
      @answer = Answer.create!(answer_params)

      if @next_question.nil?
        redirect_to @answer.question.question_section
      else
        redirect_to @next_question
      end
    end

    # PATCH/PUT /answers/1
    # PATCH/PUT /answers/1.json
    def update
      # @questionnaire = Questionnaire.find(params[:answer][:questionnaire_id])

      @unique_ident = @answer.unique_ident
      @answer.update!(answer_params)
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @answer.question.question_section
      @many = @question_section.many

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        # format.html { redirect_to question_section_path(@answer.question.question_section, unique_ident: unique_ident), notice: 'Option was successfully updated.' }

        #        format.html { render 'update.js.erb'}
        format.js
        format.json
      end
    end

    # DELETE /answers/1
    # DELETE /answers/1.json
    def destroy
      @answer.destroy
      respond_to do |format|
        format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @question = @answer.question
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      new_answer = params[:choice]

      @answer.update_on_button_press(new_answer)

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          partial = ''

          if @question.question_type == Question::TEXT_ON_YES
            partial = 'aflier_survey/questions/text_on_yes'
          elsif @question.question_type == Question::YES_OR_NO
            partial = 'aflier_survey/questions/yes_or_no'
          elsif @question.question_type == Question::OUT_OF
            partial = 'aflier_survey/questions/out_of'
          end

          render json: {
            html: render_to_string(partial: partial,
                                   formats: :html,
                                   locals: { locked: false, question: @question, answer: @answer })
          }
        end
      end
    end

    def option_choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire  = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section if @answer.question.question_section.many?

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.option_answers.find_or_create_by!(option_id: params[:option_id], unique_ident: @unique_ident)
        @answer.update_attribute(:other, false)
      else
        @option_answers = @answer.option_answers.where(option_id: params[:option_id])
        if @option_answers.empty?
          @answer.option_answers.create!(option_id: params[:option_id], unique_ident: @unique_ident)
        else
          @option_answers.destroy_all
        end
      end

      @question = @answer.question
      @answer.update(not_sure: false)

      @required_warning = @question.is_required?(@unique_ident)
      # @questionnaire.updated_questionnaire(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end
        end
      end
    end

    def other
      #      @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.update(other: true)
      else
        @answer.update(other: !@answer.other)
      end

      respond_to do |format|
        format.html
        format.json do

          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end

        end
      end

      # @questionnaire.updated_questionnaire(@unique_ident)
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :a_string, :some_text, :a_decimal, :an_integer, :a_date,
                                     :a_time, :file)
    end
  end

end

app/controllers/aflier_survey/application_controller.rb
module AflierSurvey
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    layout 'questionnaire'
  end
end

app/controllers/aflier_survey/belonging_sections_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class BelongingSectionsController < ApplicationController
    before_action :set_belonging_section, only: [:up, :destroy]

    def up
      @previous_belonging_section = @belonging_section.questionnaire.belonging_sections.find_by(position: @belonging_section.position - 1)
      @previous_belonging_section.update_attribute(:position, @belonging_section.position)
      @belonging_section.update_attribute(:position, @belonging_section.position - 1)

      redirect_to edit_questionnaire_path(@belonging_section.questionnaire)
    end

    def destroy
      @questionnaire = @belonging_section.questionnaire
      @belonging_section.destroy

      redirect_to edit_questionnaire_path(@questionnaire)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_belonging_section
      @belonging_section = BelongingSection.find(params[:id])
    end
  end

end

app/controllers/aflier_survey/calc_inputs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcInputsController < ApplicationController
    before_action :set_calc_input, only: [:show, :edit, :update, :destroy]

    # GET /calc_inputs
    def index
      @calc_inputs = CalcInput.all
    end

    # GET /calc_inputs/1
    def show
    end

    # GET /calc_inputs/new
    def new
      @calc_input = CalcInput.new
    end

    # GET /calc_inputs/1/edit
    def edit
    end

    # POST /calc_inputs
    def create
      @calc_input = CalcInput.new(calc_input_params)

      if @calc_input.save
        redirect_to @calc_input, notice: 'Calc input was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /calc_inputs/1
    def update
      if @calc_input.update(calc_input_params)
        redirect_to @calc_input, notice: 'Calc input was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /calc_inputs/1
    def destroy
      @calc_input.destroy
      redirect_to calc_inputs_url, notice: 'Calc input was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_calc_input
        @calc_input = CalcInput.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def calc_input_params
        params.require(:calc_input).permit(:calc_id, :calc_input_id)
      end
  end
end

app/controllers/aflier_survey/calcs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcsController < ApplicationController
    before_action :set_calc, only: [:show, :edit, :update, :destroy, :var_one, :var_two, :operator, :calc_one,
                                    :calc_two, :choice, :grouping, :question_choice]

    # GET /calcs
    # GET /calcs.json
    def index
      @calcs = Calc.all.order(:name)
      @calc = Calc.new
    end

    # GET /calcs/1
    # GET /calcs/1.json
    def show
      if @calc.operation == Calc::ADD
        if @calc.calc_first
          @calc.calc_inputs.create(calc_input_id: @calc.first_calc_id)
          @calc.update_attribute(:first_calc_id, nil)
        end

        if @calc.calc_second
          @calc.calc_inputs.create(calc_input_id: @calc.second_calc_id)
          @calc.update_attribute(:second_calc_id, nil)
        end

        if @calc.question_first
          @calc.question_inputs.create(question_id: @calc.first_question_id)
          @calc.update_attribute(:first_question_id, nil)
        end

        if @calc.question_second
          @calc.question_inputs.create(question_id: @calc.second_question_id)
          @calc.update_attribute(:second_question_id, nil)
        end
      end
    end

    # GET /calcs/new
    def new
      @calc = Calc.new
    end

    # GET /calcs/1/edit
    def edit
    end

    # POST /calcs
    # POST /calcs.json
    def create
      @calc = Calc.new(calc_params)

      respond_to do |format|
        if @calc.save!
          format.html { redirect_to @calc, notice: 'Calc was successfully created.' }
          format.json { render :show, status: :created, location: @calc }
        else
          format.html { render :new }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /calcs/1
    # PATCH/PUT /calcs/1.json
    def update
      respond_to do |format|
        if @calc.update(calc_params)
          format.html { redirect_to @calc, notice: 'Calc was successfully updated.' }
          format.json { render :show, status: :ok, location: @calc }
        else
          format.html { render :edit }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /calcs/1
    # DELETE /calcs/1.json
    def destroy
      @calc.destroy
      respond_to do |format|
        format.html { redirect_to calcs_url, notice: 'Calc was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def var_one
      if @calc.operation == Calc::ADD or
          @calc.operation == Calc::CHOICE or
          @calc.operation == Calc::LOWEST

        existing_calc = @calc.question_inputs.find_by(question_id: params[:question_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.question_inputs.find_or_create_by!(question_id: params[:question_id])
        end
      else
        @calc.update_attributes(first_question_id: params[:question_id], first_calc_id: nil)
      end

      redirect_to @calc
    end

    def var_two
      @calc.update_attributes(second_question_id: params[:question_id], second_calc_id: nil)

      redirect_to @calc
    end

    def calc_one
      if @calc.operation == Calc::ADD or @calc.operation == Calc::CHOICE
        existing_calc = @calc.calc_inputs.find_by(calc_input_id: params[:calc_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.calc_inputs.find_or_create_by(calc_input_id: params[:calc_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def grouping
      if @calc.operation == Calc::COLLECTION
        result_grouping = @calc.grouping_inputs.find_by(result_grouping_id: params[:result_grouping_id])

        if result_grouping
          result_grouping.destroy
        else
          @calc.grouping_inputs.find_or_create_by(result_grouping_id: params[:result_grouping_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def calc_two
      @calc.update_attributes(second_calc_id: params[:calc_id], second_question_id: nil)

      redirect_to @calc
    end

    def operator
      @calc.update_attribute(:operation, params[:operator])
      redirect_to @calc
    end

    def choice
      @calc_choice = @calc.calc_choices.find_or_create_by!(option_id: params[:option_id])
      @calc_choice.update_attributes(calc_result_id: params[:calc_result_id])

      redirect_to @calc
    end

    def question_choice
      @question_choice = @calc.question_choices.find_or_create_by!(option_id: params[:option_id])
      @question_choice.update_attributes(question_id: params[:question_id])

      redirect_to @calc
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_calc
      @calc = Calc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calc_params
      params.require(:calc).permit(:name, :first_question_id, :second_question_id, :operation, :a_decimal,
                                   :treat_repeat)
    end
  end
end

app/views/aflier_survey/calcs/_form.html.erb
<%= simple_form_for(@calc) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn-block" %>
<% end %>

app/views/aflier_survey/calcs/_operator.html.erb
<h2>Operator</h2>

<% AflierSurvey::Calc::OPERATORS.each do |operator| %>
  <%= link_to operator.capitalize, operator_calc_path(@calc, operator: operator), class: "btn #{ operator == @calc.operation ? 'btn-primary' : 'btn-outline-secondary'} btn-block" %>
<% end %>

app/views/aflier_survey/calcs/_values_from_answers.html.erb
<h3>Values from Answers</h3>

<% QuestionSection.all.order(:name).each do |question_section| %>
  <div class="card">

    <div class="card-header" data-toggle="collapse" data-target="#section-<%= question_section.id %>" aria-expanded="false" aria-controls="collapseExample">
      <%= question_section.name %>
    </div>

    <div id="section-<%= question_section.id %>" class="collapse card-body">
      <% unless question_section.questions.where(question_type: Question::CALCULATION_TYPE).empty? %>
        <% question_section.questions.where(question_type: Question::CALCULATION_TYPE).order(:position).each do |question| %>
          <div class="row">
            <div class="col-md-9">
              <%= link_to raw('<i class="fas fa-chevron-circle-right"></i>'), question %>
              <% if @calc.is_first_question?(question) %>
                <%= link_to raw('<i class="far fa-dot-circle"></i> ' + question.name), var_one_calc_path(@calc, question_id: question.id) %><br>
              <% else %>
                <%= link_to raw('<i class="far fa-circle"></i> ' + question.name), var_one_calc_path(@calc, question_id: question.id) %><br>
              <% end %>

              <% if @calc.is_first_question?(question) %>
                <script>
                    $('#section-<%= question_section.id %>').collapse('show');
                </script>
              <% end %>
            </div>
            <div class="col-md-3">
              <% if question_input = @calc.get_question_input(question) %>
                <% if question_input.subtract %>
                  <%= link_to 'Subtract', toggle_subtract_question_input_path(question_input), class: 'btn btn-block btn-outline-warning' %>
                <% else %>
                  <%= link_to 'Add', toggle_subtract_question_input_path(question_input), class: 'btn btn-block btn-outline-primary' %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/aflier_survey/calcs/edit.html.erb
<h1>Edit Calc</h1>

<div class="row justify-content-md-center">
  <div class="col-md-6">
    <%= simple_form_for(@calc) do |f| %>
      <%= f.input :name %>
      <%= f.input :first_question_id %>
      <%= f.input :second_question_id %>
      <%= f.input :operation %>
      <%= f.input :treat_repeat, collection: ['sum'] %>

      <%= f.button :submit, class: "btn-block" %>
    <% end %>
  </div>
</div>

app/views/aflier_survey/calcs/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>New Calc</h1>
		</div>
	</div>
</div>

<%= render 'form' %>

app/views/aflier_survey/calcs/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1><%= @calc.name %></h1>
		</div>
		
		<ol class="breadcrumb">
		  <li class="breadcrumb-item"><%= link_to "All", calcs_path %></li>
		  <li class="breadcrumb-item active"><%= @calc.name %></li>
		</ol>

    <div class="alert alert-success text-center" role="alert">
      <%= raw @calc.in_words %>
    </div>

	</div>

</div>

<div class="row">
  <% if @calc.operation.nil? %>
    <div class="col-md-3">
      <%= render 'operator' %>
    </div>
    <div class="col-md-6">
    </div>
  <% elsif @calc.operation == AflierSurvey::Calc::COLLECTION %>
    <div class="col-md-3">
      <%= render 'operator' %>
    </div>
    <div class="col-md-6">
      <h2>Result Groupings</h2>

      <% ResultGrouping.all.order(:name).each do |result_grouping| %>
        <p><%= link_to result_grouping.name, grouping_calc_path(@calc, result_grouping_id: result_grouping.id), class: " btn #{ @calc.is_grouping?(result_grouping) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %> </p>
      <% end %>
    </div>
  <% elsif @calc.operation == AflierSurvey::Calc::CHOICE %>
    <div class="col-md-3">
      <%= render 'operator' %>
    </div>
    <div class="col-md-3">
      <h2>Variables</h2>

      <p>What calculation would you like to make a choice between</p>

      <h3>Previous calculation</h3>

      <% Calc.all.order(:name).each do |calc| %>
        <% unless calc.id == @calc.id %>
          <p><%= link_to calc.name, calc_one_calc_path(@calc, calc_id: calc.id), class: " btn #{ @calc.is_first_calc?(calc) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %> </p>
        <% end %>
      <% end %>

      <h3>Questions</h3>

      <%= render 'values_from_answers' %>
    </div>
    <div class="col-md-3">
      <h2>Selector</h2>
      <p>Choose the question that will decide the value used.</p>

      <% AflierSurvey::QuestionSection.all.order(:name).each do |question_section| %>
        <h4><%= question_section.name %></h4>

        <% question_section.questions.where(question_type: AflierSurvey::Question::OPTION_TYPE).order(:name).each do |question| %>
          <p><%= link_to question.name, var_two_calc_path(@calc, question_id: question.id), class: " btn #{ @calc.is_second_question?(question) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %></p>
          <% if @calc.is_second_question?(question) %>

            <% question.options.each do |option| %>
              <table class="table">
                <tr>
                  <th><%= option.name %></th>
                  <th></th>
                </tr>

                <% @calc.the_calcs.each do |calc| %>
                  <tr>
                    <td><%= calc.name %></td>
                    <td>
                      <div class="float-right">
                        <%= link_to raw("#{ @calc.this_option?(calc, option) ? '<i class="far fa-check-square"></i>' : '<i class="far fa-square"></i>'}"), choice_calc_path(@calc, calc_result_id: calc.id, option_id: option.id) %>
                      </div>
                    </td>
                  </tr>
                <% end %>

                <% @calc.questions.each do |question| %>
                  <tr>
                    <td><%= question.name %></td>
                    <td>
                      <div class="float-right">
                        <%= link_to raw("#{ @calc.this_question?(question, option) ? '<i class="far fa-check-square"></i>' : '<i class="far fa-square"></i>'}"), question_choice_calc_path(@calc, question_id: question.id, option_id: option.id) %>
                      </div>
                    </td>
                  </tr>
                <% end %>


              </table>

            <% end %>

          <% end %>
        <% end %>
      <% end %>

      </div>

  <% elsif @calc.operation == AflierSurvey::Calc::ADD or @calc.operation == AflierSurvey::Calc::LOWEST %>
    <div class="col-md-3">
      <%= render 'operator' %>
    </div>
    <div class="col-md-6">
      <h2>Variables</h2>

      <% if @calc.operation == AflierSurvey::Calc::ADD %>
        <h3>Previous calculation</h3>

        <% AflierSurvey::Calc.all.order(:name).each do |calc| %>
          <% unless calc.id == @calc.id %>
            <p><%= link_to calc.name, calc_one_calc_path(@calc, calc_id: calc.id), class: " btn #{ @calc.is_first_calc?(calc) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %> </p>
          <% end %>
        <% end %>
      <% end %>

      <%= render 'values_from_answers' %>
    </div>
  <% else %>
    <div class="col-md-3">
      <% if @calc.operation == AflierSurvey::Calc::ADD %>

      <% elsif not(@calc.operation == AflierSurvey::Calc::CONSTANT) %>
        <h2>First Variable</h2>

        <h3>Previous calculation</h3>

        <% Calc.all.order(:name).each do |calc| %>
          <p><%= link_to calc.name, calc_one_calc_path(@calc, calc_id: calc.id), class: " btn #{ @calc.is_first_calc?(calc) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %> </p>
        <% end %>

        <%= render 'values_from_answers' %>
      <% end %>
    </div>
    <div class="col-md-3">
      <%= render 'operator' %>
    </div>
    <div class="col-md-3">
      <% if @calc.operation == AflierSurvey::Calc::CONSTANT %>
        <h2>Value</h2>
        <%= simple_form_for(@calc) do |f| %>
          <%= f.input :a_decimal, label: false %>
          <%= f.button :submit, class: "btn-block" %>
        <% end %>
      <% elsif @calc.operation == AflierSurvey::Calc::ADD %>
        <div class="alert alert-info">
          Two or more previous calculation can be added together.
        </div>
      <% else %>
        <h2>Second Variable</h2>

        <h3>Previous calculation</h3>

        <% AflierSurvey::Calc.all.order(:name).each do |calc| %>
          <p><%= link_to calc.name, calc_two_calc_path(@calc, calc_id: calc.id), class: " btn #{ @calc.is_second_calc?(calc) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %> </p>
        <% end %>

        <h3>Values</h3>

        <% AflierSurvey::QuestionSection.all.order(:name).each do |question_section| %>
          <div class="card">
            <div class="card-header" data-toggle="collapse" data-target="#section-second-<%= question_section.id %>" aria-expanded="false" aria-controls="collapseExample">
              <%= question_section.name %>
            </div>
            <div id="section-second-<%= question_section.id %>" class="collapse card-body">
              <% question_section.questions.where(question_type: Question::CALCULATION_TYPE).order(:name).each do |question| %>
                <%= link_to raw('<i class="fas fa-chevron-circle-right"></i>'), question %>
                <% if @calc.is_second_question?(question) %>
                  <%= link_to raw('<i class="far fa-dot-circle"></i> ' + question.name), var_two_calc_path(@calc, question_id: question.id) %><br>
                <% else %>
                  <%= link_to raw('<i class="far fa-circle"></i> ' + question.name), var_two_calc_path(@calc, question_id: question.id) %><br>
                <% end %>
                <% if @calc.is_second_question?(question) %>
                  <script>
                      $('#section-second-<%= question_section.id %>').collapse('show');
                  </script>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="col-md-3">
    <div class="card">
      <div class="card-header">Behaviour</div>
      <div class="card-body">
        <p><b>Treat Repeat:</b> <%= @calc.treat_repeat %></p>
      </div>
      <div class="card-footer">
        <%= link_to 'Edit', edit_calc_path(@calc), class: "btn btn-outline-secondary" %>
      </div>
    </div>

    <div class="alert alert-info mt-1">
      <p><b>Note:</b> Setting "Treat Repeat" can be used when the calculation is a '/' or 'x' where the values being used are from the same question section
        that is 'many'. Setting it to "Sum" will mean the calculation is done on each repeated section and then they are all summed together.</p>
      <p>Left blank the last values will be used.</p>
    </div>
  </div>
</div>