config/routes.rb
AflierSurvey::Engine.routes.draw do


  devise_for :users, class_name: "User"

  resources :answers do
    member do
      get :choice
      get :option_choice
      get :other
    end
  end

  resources :choice_answers
  resources :option_answers
  resources :questionnaire_submissions
  resources :repeat_sections
  resources :section_progresses

  resources :question_inputs do
    member do
      get :toggle_subtract
    end
  end

  resources :calc_inputs

  resources :belonging_sections do
    member do
      get :up
    end
  end

  resources :options do
    member do
      get :up
    end
  end


  resources :questions do
    resources :options

    member do
      get :up
      get :down
      get :toggle_other
      get :type
      get :result
      get :following
      get :calc
      get :clone
      get :feed
      get :grouping
      get :toggle_input
    end
  end

  resources :calcs do
    member do
      get :var_one
      get :var_two
      get :calc_one
      get :calc_two
      get :operator
      get :choice
      get :question_choice
      get :grouping
    end
  end

  resources :question_sections do
    resources :questions

    member do
      get :report
      get :repeat
      get :complete
      get :include
      get :exclude
    end
  end

  resources :questionnaires do
    member do
      get :submit
      get :assign
      get :save
      get :toggle_input
    end
  end
end

app/models/aflier_survey/application_record.rb
module AflierSurvey
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/aflier_survey/belonging_section.rb
module AflierSurvey
  class BelongingSection < ApplicationRecord
    belongs_to :questionnaire
    belongs_to :question_section
  end
end

app/models/aflier_survey/calc_input.rb
module AflierSurvey
  class CalcInput < ApplicationRecord
  end
end

app/models/aflier_survey/option.rb
module AflierSurvey
  class Option < ApplicationRecord
    belongs_to :question

    has_many :option_mappings
    has_many :option_answers
  end
end

app/models/aflier_survey/option_answer.rb
module AflierSurvey
  class OptionAnswer < ApplicationRecord
    belongs_to :answer
  end
end

app/models/aflier_survey/question_input.rb
module AflierSurvey
  class QuestionInput < ApplicationRecord
    belongs_to :calc
    belongs_to :question
  end
end

app/models/aflier_survey/questionnaire_submission.rb
module AflierSurvey
  class QuestionnaireSubmission < ApplicationRecord
    belongs_to :questionnaire

    validates :unique_ident, presence: true

    SAVED      = 'saved'
    SUBMITTED  = 'submitted'
    UPDATED    = 'updated'
    LOOKING_AT = 'looking_at'
    ASSIGNED   = 'assigned'
  end

end

app/models/aflier_survey/section_progress.rb
module AflierSurvey
  class SectionProgress < ApplicationRecord
    belongs_to :question_section

    COMPLETE = 'complete'.freeze
    UPDATED = 'updated'.freeze
    REQUIRED = 'required'.freeze
  end
end

app/controllers/aflier_survey/answers_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class AnswersController < ApplicationController
    before_action :set_answer, only: [:show, :edit, :update, :destroy, :choice, :option_choice, :other]

    skip_before_action :verify_authenticity_token

    # GET /answers
    # GET /answers.json
    def index
      @answers = Answer.all
    end

    # GET /answers/1
    # GET /answers/1.json
    def show
    end

    # GET /answers/new
    def new
      @answer = Answer.new
    end

    # GET /answers/1/edit
    def edit
    end

    # POST /answers
    # POST /answers.json
    def create
      @answer = Answer.create!(answer_params)

      if @next_question.nil?
        redirect_to @answer.question.question_section
      else
        redirect_to @next_question
      end
    end

    # PATCH/PUT /answers/1
    # PATCH/PUT /answers/1.json
    def update
      # @questionnaire = Questionnaire.find(params[:answer][:questionnaire_id])

      @unique_ident = @answer.unique_ident
      @answer.update!(answer_params)
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @answer.question.question_section
      @many = @question_section.many

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        # format.html { redirect_to question_section_path(@answer.question.question_section, unique_ident: unique_ident), notice: 'Option was successfully updated.' }

        #        format.html { render 'update.js.erb'}
        format.js
        format.json
      end
    end

    # DELETE /answers/1
    # DELETE /answers/1.json
    def destroy
      @answer.destroy
      respond_to do |format|
        format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @question = @answer.question
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      new_answer = params[:choice]

      @answer.update_on_button_press(new_answer)

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          partial = ''

          if @question.question_type == Question::TEXT_ON_YES
            partial = 'aflier_survey/questions/text_on_yes'
          elsif @question.question_type == Question::YES_OR_NO
            partial = 'aflier_survey/questions/yes_or_no'
          elsif @question.question_type == Question::OUT_OF
            partial = 'aflier_survey/questions/out_of'
          end

          render json: {
            html: render_to_string(partial: partial,
                                   formats: :html,
                                   locals: { locked: false, question: @question, answer: @answer })
          }
        end
      end
    end

    def option_choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire  = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section if @answer.question.question_section.many?

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.option_answers.find_or_create_by!(option_id: params[:option_id], unique_ident: @unique_ident)
        @answer.update_attribute(:other, false)
      else
        @option_answers = @answer.option_answers.where(option_id: params[:option_id])
        if @option_answers.empty?
          @answer.option_answers.create!(option_id: params[:option_id], unique_ident: @unique_ident)
        else
          @option_answers.destroy_all
        end
      end

      @question = @answer.question
      @answer.update(not_sure: false)

      @required_warning = @question.is_required?(@unique_ident)
      # @questionnaire.updated_questionnaire(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end
        end
      end
    end

    def other
      #      @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.update(other: true)
      else
        @answer.update(other: !@answer.other)
      end

      respond_to do |format|
        format.html
        format.json do

          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end

        end
      end

      # @questionnaire.updated_questionnaire(@unique_ident)
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :a_string, :some_text, :a_decimal, :an_integer, :a_date,
                                     :a_time, :file)
    end
  end

end

app/controllers/aflier_survey/application_controller.rb
module AflierSurvey
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    layout 'questionnaire'
  end
end

app/controllers/aflier_survey/belonging_sections_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class BelongingSectionsController < ApplicationController
    before_action :set_belonging_section, only: [:up, :destroy]

    def up
      @previous_belonging_section = @belonging_section.questionnaire.belonging_sections.find_by(position: @belonging_section.position - 1)
      @previous_belonging_section.update_attribute(:position, @belonging_section.position)
      @belonging_section.update_attribute(:position, @belonging_section.position - 1)

      redirect_to edit_questionnaire_path(@belonging_section.questionnaire)
    end

    def destroy
      @questionnaire = @belonging_section.questionnaire
      @belonging_section.destroy

      redirect_to edit_questionnaire_path(@questionnaire)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_belonging_section
      @belonging_section = BelongingSection.find(params[:id])
    end
  end

end

app/controllers/aflier_survey/calc_inputs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcInputsController < ApplicationController
    before_action :set_calc_input, only: [:show, :edit, :update, :destroy]

    # GET /calc_inputs
    def index
      @calc_inputs = CalcInput.all
    end

    # GET /calc_inputs/1
    def show
    end

    # GET /calc_inputs/new
    def new
      @calc_input = CalcInput.new
    end

    # GET /calc_inputs/1/edit
    def edit
    end

    # POST /calc_inputs
    def create
      @calc_input = CalcInput.new(calc_input_params)

      if @calc_input.save
        redirect_to @calc_input, notice: 'Calc input was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /calc_inputs/1
    def update
      if @calc_input.update(calc_input_params)
        redirect_to @calc_input, notice: 'Calc input was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /calc_inputs/1
    def destroy
      @calc_input.destroy
      redirect_to calc_inputs_url, notice: 'Calc input was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_calc_input
        @calc_input = CalcInput.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def calc_input_params
        params.require(:calc_input).permit(:calc_id, :calc_input_id)
      end
  end
end

app/controllers/aflier_survey/calcs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcsController < ApplicationController
    before_action :set_calc, only: [:show, :edit, :update, :destroy, :var_one, :var_two, :operator, :calc_one,
                                    :calc_two, :choice, :grouping, :question_choice]

    # GET /calcs
    # GET /calcs.json
    def index
      @calcs = Calc.all.order(:name)
      @calc = Calc.new
    end

    # GET /calcs/1
    # GET /calcs/1.json
    def show
      if @calc.operation == Calc::ADD
        if @calc.calc_first
          @calc.calc_inputs.create(calc_input_id: @calc.first_calc_id)
          @calc.update_attribute(:first_calc_id, nil)
        end

        if @calc.calc_second
          @calc.calc_inputs.create(calc_input_id: @calc.second_calc_id)
          @calc.update_attribute(:second_calc_id, nil)
        end

        if @calc.question_first
          @calc.question_inputs.create(question_id: @calc.first_question_id)
          @calc.update_attribute(:first_question_id, nil)
        end

        if @calc.question_second
          @calc.question_inputs.create(question_id: @calc.second_question_id)
          @calc.update_attribute(:second_question_id, nil)
        end
      end
    end

    # GET /calcs/new
    def new
      @calc = Calc.new
    end

    # GET /calcs/1/edit
    def edit
    end

    # POST /calcs
    # POST /calcs.json
    def create
      @calc = Calc.new(calc_params)

      respond_to do |format|
        if @calc.save!
          format.html { redirect_to @calc, notice: 'Calc was successfully created.' }
          format.json { render :show, status: :created, location: @calc }
        else
          format.html { render :new }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /calcs/1
    # PATCH/PUT /calcs/1.json
    def update
      respond_to do |format|
        if @calc.update(calc_params)
          format.html { redirect_to @calc, notice: 'Calc was successfully updated.' }
          format.json { render :show, status: :ok, location: @calc }
        else
          format.html { render :edit }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /calcs/1
    # DELETE /calcs/1.json
    def destroy
      @calc.destroy
      respond_to do |format|
        format.html { redirect_to calcs_url, notice: 'Calc was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def var_one
      if @calc.operation == Calc::ADD or
          @calc.operation == Calc::CHOICE or
          @calc.operation == Calc::LOWEST

        existing_calc = @calc.question_inputs.find_by(question_id: params[:question_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.question_inputs.find_or_create_by!(question_id: params[:question_id])
        end
      else
        @calc.update_attributes(first_question_id: params[:question_id], first_calc_id: nil)
      end

      redirect_to @calc
    end

    def var_two
      @calc.update_attributes(second_question_id: params[:question_id], second_calc_id: nil)

      redirect_to @calc
    end

    def calc_one
      if @calc.operation == Calc::ADD or @calc.operation == Calc::CHOICE
        existing_calc = @calc.calc_inputs.find_by(calc_input_id: params[:calc_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.calc_inputs.find_or_create_by(calc_input_id: params[:calc_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def grouping
      if @calc.operation == Calc::COLLECTION
        result_grouping = @calc.grouping_inputs.find_by(result_grouping_id: params[:result_grouping_id])

        if result_grouping
          result_grouping.destroy
        else
          @calc.grouping_inputs.find_or_create_by(result_grouping_id: params[:result_grouping_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def calc_two
      @calc.update_attributes(second_calc_id: params[:calc_id], second_question_id: nil)

      redirect_to @calc
    end

    def operator
      @calc.update_attribute(:operation, params[:operator])
      redirect_to @calc
    end

    def choice
      @calc_choice = @calc.calc_choices.find_or_create_by!(option_id: params[:option_id])
      @calc_choice.update_attributes(calc_result_id: params[:calc_result_id])

      redirect_to @calc
    end

    def question_choice
      @question_choice = @calc.question_choices.find_or_create_by!(option_id: params[:option_id])
      @question_choice.update_attributes(question_id: params[:question_id])

      redirect_to @calc
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_calc
      @calc = Calc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calc_params
      params.require(:calc).permit(:name, :first_question_id, :second_question_id, :operation, :a_decimal,
                                   :treat_repeat)
    end
  end
end

app/views/aflier_survey/question_sections/_card_footer.html.erb
<% if false %>

<% if questionnaire.complete_on_sections %>

  <div class="card-footer text-right" id="card-footer-<%= question_section.id %>">
    <% if question_section.is_complete?(user) %>
      <i class="far fa-check-square" aria-hidden="true"></i>
    <% else %>
      <%= link_to 'Complete', complete_question_section_path(question_section, user_id: user.id), class: "btn btn-sm btn-outline-primary", remote: true %>
    <% end %>
  </div>

<% end %>

<% end %>

app/views/aflier_survey/question_sections/_edit_form.html.erb
<button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#newquestion_section">Edit</button>

<div class="modal fade" id="newquestion_section" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <%= simple_form_for(@question_section) do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Question section</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= f.input :name %>
          <div class="mb-3">
            <label>Section Description</label>
            <%= f.rich_text_area :section_description %>
          </div>
          <%= f.input :restrict_controls %>
          <%= f.input :default_open %>
          <h4>Repeated Section</h4>
          <%= f.input :many %>
          <%= f.input :repeat_has_date  %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/aflier_survey/question_sections/_following_section.html.erb
<% if false %>

<div id="following-section-<%= question_section.id %>">
  <% question_section.questions.where(question_type: [AflierSurvey::Question::SECTION_ON_YES, AflierSurvey::Question::SECTION_ON_NO]).each do |question| %>
      <%= render question.following_section, questionnaire: questionnaire, unique_ident: unique_ident if question.answer_wants_section?(unique_ident) %>
  <% end %>
</div>

<% end %>

app/views/aflier_survey/question_sections/_form.html.erb
<%= simple_form_for(@question_section) do |f| %>
  <%= render 'aflier_survey/bootstrap/modal',
             btn_title: "New Question section", f: f do %>
    <%= f.input :name %>
    <%= f.input :description %>
  <% end %>
<% end %>

app/views/aflier_survey/question_sections/_form_create.html.erb
<%= form_with model: AflierSurvey::QuestionSection.new, local: false,
              data: { target: "supertable.submit",
                      action: "submit->supertable#preventSubmit" } do |form| %>
  <div class="input-group mb-3">
    <%= form.text_field :name, class: 'form-control' %>
    <button data-action="click->supertable#submitForm"
            class="btn btn-primary btn-sm"
            value="Create Comment">Create</button>
  </div>
<% end %>

app/views/aflier_survey/question_sections/_question_section.html.erb
<div class="card shadow mb-3" id="question-section-<%= question_section.id %>"
     data-refresh="<%= 'yes' if question_section.question %>"
     data-path="<%= aflier_survey.question_section_path(question_section, unique_ident: unique_ident, show_required: true) %>"
     data-aflier-survey-target="questionSection"
     <%= 'hidden' unless question_section.can_view?(unique_ident) %>>
  <div class="card-header" role="tab" id="headingOne">
    <h5 class="mb-0">
      <a data-bs-toggle="collapse" href="#collapse<%= question_section.id %>" aria-expanded="true" aria-controls="collapseOne">
        <% if question_section.is_complete?(unique_ident) %><i id="complete-<%= question_section.id %>" class="fas fa-star float-right" aria-hidden="true" style="color: gold;"></i><% end %>
        <% if question_section.is_required?(unique_ident) %>
          <i id="complete-<%= question_section.id %>" class="fas fa-exclamation-triangle float-right" aria-hidden="true" style="color: darkred;"></i>

          <% if current_user.admin %>
            <% questionnaire.incomplete_answers(unique_ident).each do |answer| %>
              <p>answer.id <%= answer.id %> for "<%= answer.question.name %>" repeated_section "<%= answer.repeat_section_id %>"</p>
            <% end %>
          <% end %>

        <% end %>
        <%= question_section.name %>
      </a>
    </h5>
  </div>

  <div id="collapse<%= question_section.id %>" class="collapse <%= question_section.open_section?(unique_ident) ? 'show' : '' %>" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
    <div class="card-body">
      <%= render 'aflier_survey/alerts/alert__info' do %>
        <%= question_section.section_description %>
      <% end unless only_answers or question_section.section_description.blank?%>

      <% if question_section.many %>
          <div id="repeat-question-section-<%= question_section.id %>">
            <%= render question_section.repeated_sections(unique_ident),
                       questionnaire: questionnaire,
                       unique_ident: unique_ident,
                       show_required: show_required,
                       last_count: question_section.repeated_sections(unique_ident).size - 1, admin: false %>
          </div>

          <%= link_to "Add", aflier_survey.repeat_question_section_path(question_section,
                                                                        questionnaire_id: questionnaire.id,
                                                                        unique_ident: unique_ident), remote: true, class: "btn btn-primary" if question_section.can_control_repeated_section? %>
      <% else %>
          <% question_section.questions.includes(:question_y).order(:position).each do |question| %>
              <%= render question, unique_ident: unique_ident, admin: admin, locked: locked,
                         show_required: show_required %>
          <% end %>
      <% end %>
    </div>
    <%= render 'aflier_survey/question_sections/card_footer', question_section: question_section, user: user if false %>
  </div>
</div>

<%= render 'aflier_survey/question_sections/following_section', question_section: question_section, unique_ident: unique_ident %>

app/views/aflier_survey/question_sections/_question_section_tr.html.erb
<tr>
  <td><%= link_to question_section.name, edit_question_section_path(question_section) %></td>
  <td class="text-end">
      <%= link_to icons__trash, question_section, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
  </td>
</tr>

app/views/aflier_survey/question_sections/complete.js.erb
$('#collapse<%= @question_section.id %>').collapse('hide');

$('#collapse<%= @question_section.id %>').on('hidden.bs.collapse', function () {
    $('#question-section-<%= @question_section.id %>').replaceWith('<%= j render @question_section, user: @user %>');
})

app/views/aflier_survey/question_sections/edit.html.erb
<h1>Editing <%= @question_section.name %></h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to 'All Sections', question_sections_path %></li>
  <li class="breadcrumb-item active"><%= @question_section.name %></li>
</ol>

<div class="row">
  <div class="col-md-9">
    <div class="card shadow mb-3">
      <div class="card-header">Question</div>
      <div class="card-body">
        <table class="table">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Question type</th>
            <th>Question section</th>
            <th>Required</th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @questions.order(:position).each do |question| %>
            <tr>
              <td><%= question.position %></td>
              <td><%= link_to question.name, edit_question_path(question) %></td>
              <td><%= question.question_type %></td>
              <td><%= question.question_section.name %></td>
              <td><%= tick question.required %></td>
              <td class="text-end">
                <div class="btn-group">
                  <%= link_to icons__up, up_question_path(question), class: "btn btn-info btn-sm" unless question.position == 0 %>
                  <%= link_to icons__down, down_question_path(question), class: "btn btn-info btn-sm" unless question.position == @questions.size - 1 %>
                  <%= link_to icons__trash, question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                </div>
              </td>
            </tr>
          <% end %>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th><%= render '/aflier_survey/questions/form' %></th>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <h4>Description</h4>
          <%= raw @question_section.section_description %>
        </li>
        <li class="list-group-item">
          <h4>Default Open </h4>
          <%= raw @question_section.default_open %>
        </li>
        <li class="list-group-item">
          <b>Repeat Section: </b><%= tick @question_section.many %><br>
          <b>Repeat has date: </b><%= tick @question_section.repeat_has_date %><br>
          <b>Restricted Controls: </b><%= tick @question_section.restrict_controls %>
        </li>
      </ul>
      <div class="card-footer">
        <%= render 'edit_form', question_section: @question_section %>
      </div>
    </div>

    <div class="card shadow mb-3">
      <div class="card-header">Gating</div>
      <div class="card-body">
        <div class="mb-3">
          <label>Conditional Question</label>
          <%= render 'stimulus/edit_in_place/collection_select_input',
                     path: question_section_path(@question_section),
                     klass: @question_section,
                     attribute: :question_id,
                     collection: AflierSurvey::Question.all
                       .where(question_type: [AflierSurvey::Question::SELECT_ONE,
                                              AflierSurvey::Question::SELECT_MANY]) %>
        </div>
        <div class="mb-3">
          <% if @question_section.question %>
            <label>Option to Show</label>

            <%= render 'stimulus/edit_in_place/collection_select_input',
                       path: question_section_path(@question_section),
                       klass: @question_section,
                       attribute: :option_id,
                       collection: @question_section.question.options %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/aflier_survey/question_sections/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Question Sections</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="card shadow mb-3"
         data-controller="supertable"
         data-supertable-create-url="<%= question_sections_path %>"
         data-supertable-filter-url="<%=  %>">
      <div class="card-header">Question Sections</div>
      <div class="card-body">
        <table class="table">
          <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
          </thead>

          <tbody data-supertable-target="content">
          <% @question_sections.each do |question_section| %>
            <%= render 'question_section_tr', question_section: question_section %>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="card-footer">
        <%= render 'form_create' %>
      </div>
    </div>
  </div>
</div>

app/views/aflier_survey/question_sections/repeat.js.erb
<% @old_repeats.each_with_index do |repeat_section, index| %>

 $('#repeat-section-<%= repeat_section.id %>').collapse('hide');
 $('#repeat-number-<%= repeat_section.id %>').replaceWith('<span id="repeat-number"><%= index + 1 %></span>');

<% end %>

$('#repeat-question-section-<%= @repeat_section.question_section.id %>')
    .append('<%= j render 'aflier_survey/repeat_sections/repeat_section',
    questionnaire: @questionnaire, unique_ident: @repeat_section.unique_ident,
    repeat_section: @repeat_section, repeat_section_counter: @old_repeats.size - 1, last_count: @old_repeats.size - 1,
    show_required: false,
    admin: false %>');

app/views/aflier_survey/question_sections/report.html.erb
<h1><%= @question_section.name %></h1>

<% @question_section.questions.each do |question| %>
    <div class="row" style="margin-bottom: 2px">
      <div class="col-md-4">
        <%= question.name %>
      </div>
      <div class="col-md-8" style="background-color: #eee">
        <%= question.get_answer(@user) %>
      </div>
    </div>
<% end %>

app/views/aflier_survey/question_sections/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Dashboard for</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <ul class="nav flex-column nav-pills">
      <li class="nav-item">
        <a class="nav-link" href="#">Profile???</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Questionnaire', my_manage_user_path(@user), remote: true, class: "nav-link active" %>
      </li>
    </ul>
  </div>
  <div class="col-md-9">
    <%= render 'aflier_survey/questionnaires/questionnaire', questionnaire: @questionnaire, user: @user %>
  </div>

  <script>
    <% @question_section.belonging_sections.each do |belonging_section| %>
      $('#collapse<%= belonging_section.id %>').collapse('show')
    <% end %>
  </script>
</div>