config/routes.rb
AflierSurvey::Engine.routes.draw do


  devise_for :users, class_name: "User"

  resources :answers do
    member do
      get :choice
      get :option_choice
      get :other
    end
  end

  resources :choice_answers
  resources :option_answers
  resources :questionnaire_submissions
  resources :repeat_sections
  resources :section_progresses

  resources :question_inputs do
    member do
      get :toggle_subtract
    end
  end

  resources :calc_inputs

  resources :belonging_sections do
    member do
      get :up
    end
  end

  resources :options do
    member do
      get :up
    end
  end


  resources :questions do
    resources :options

    member do
      get :up
      get :down
      get :toggle_other
      get :type
      get :result
      get :following
      get :calc
      get :clone
      get :feed
      get :grouping
      get :toggle_input
    end
  end

  resources :calcs do
    member do
      get :var_one
      get :var_two
      get :calc_one
      get :calc_two
      get :operator
      get :choice
      get :question_choice
      get :grouping
    end
  end

  resources :question_sections do
    resources :questions

    member do
      get :report
      get :repeat
      get :complete
      get :include
      get :exclude
    end
  end

  resources :questionnaires do
    member do
      get :submit
      get :assign
      get :save
      get :toggle_input
    end
  end
end

app/models/aflier_survey/application_record.rb
module AflierSurvey
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/aflier_survey/belonging_section.rb
module AflierSurvey
  class BelongingSection < ApplicationRecord
    belongs_to :questionnaire
    belongs_to :question_section
  end
end

app/models/aflier_survey/calc_input.rb
module AflierSurvey
  class CalcInput < ApplicationRecord
  end
end

app/models/aflier_survey/option.rb
module AflierSurvey
  class Option < ApplicationRecord
    belongs_to :question

    has_many :option_mappings
    has_many :option_answers
  end
end

app/models/aflier_survey/option_answer.rb
module AflierSurvey
  class OptionAnswer < ApplicationRecord
    belongs_to :answer
  end
end

app/models/aflier_survey/question_input.rb
module AflierSurvey
  class QuestionInput < ApplicationRecord
    belongs_to :calc
    belongs_to :question
  end
end

app/models/aflier_survey/questionnaire_submission.rb
module AflierSurvey
  class QuestionnaireSubmission < ApplicationRecord
    belongs_to :questionnaire

    validates :unique_ident, presence: true

    SAVED      = 'saved'
    SUBMITTED  = 'submitted'
    UPDATED    = 'updated'
    LOOKING_AT = 'looking_at'
    ASSIGNED   = 'assigned'
  end

end

app/models/aflier_survey/section_progress.rb
module AflierSurvey
  class SectionProgress < ApplicationRecord
    belongs_to :question_section

    COMPLETE = 'complete'.freeze
    UPDATED = 'updated'.freeze
    REQUIRED = 'required'.freeze
  end
end

app/controllers/aflier_survey/answers_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class AnswersController < ApplicationController
    before_action :set_answer, only: [:show, :edit, :update, :destroy, :choice, :option_choice, :other]

    skip_before_action :verify_authenticity_token

    # GET /answers
    # GET /answers.json
    def index
      @answers = Answer.all
    end

    # GET /answers/1
    # GET /answers/1.json
    def show
    end

    # GET /answers/new
    def new
      @answer = Answer.new
    end

    # GET /answers/1/edit
    def edit
    end

    # POST /answers
    # POST /answers.json
    def create
      @answer = Answer.create!(answer_params)

      if @next_question.nil?
        redirect_to @answer.question.question_section
      else
        redirect_to @next_question
      end
    end

    # PATCH/PUT /answers/1
    # PATCH/PUT /answers/1.json
    def update
      # @questionnaire = Questionnaire.find(params[:answer][:questionnaire_id])

      @unique_ident = @answer.unique_ident
      @answer.update!(answer_params)
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @answer.question.question_section
      @many = @question_section.many

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        # format.html { redirect_to question_section_path(@answer.question.question_section, unique_ident: unique_ident), notice: 'Option was successfully updated.' }

        #        format.html { render 'update.js.erb'}
        format.js
        format.json
      end
    end

    # DELETE /answers/1
    # DELETE /answers/1.json
    def destroy
      @answer.destroy
      respond_to do |format|
        format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @question = @answer.question
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      new_answer = params[:choice]

      @answer.update_on_button_press(new_answer)

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          partial = ''

          if @question.question_type == Question::TEXT_ON_YES
            partial = 'aflier_survey/questions/text_on_yes'
          elsif @question.question_type == Question::YES_OR_NO
            partial = 'aflier_survey/questions/yes_or_no'
          elsif @question.question_type == Question::OUT_OF
            partial = 'aflier_survey/questions/out_of'
          end

          render json: {
            html: render_to_string(partial: partial,
                                   formats: :html,
                                   locals: { locked: false, question: @question, answer: @answer })
          }
        end
      end
    end

    def option_choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire  = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section if @answer.question.question_section.many?

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.option_answers.find_or_create_by!(option_id: params[:option_id], unique_ident: @unique_ident)
        @answer.update_attribute(:other, false)
      else
        @option_answers = @answer.option_answers.where(option_id: params[:option_id])
        if @option_answers.empty?
          @answer.option_answers.create!(option_id: params[:option_id], unique_ident: @unique_ident)
        else
          @option_answers.destroy_all
        end
      end

      @question = @answer.question
      @answer.update(not_sure: false)

      @required_warning = @question.is_required?(@unique_ident)
      # @questionnaire.updated_questionnaire(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end
        end
      end
    end

    def other
      #      @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.update(other: true)
      else
        @answer.update(other: !@answer.other)
      end

      respond_to do |format|
        format.html
        format.json do

          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end

        end
      end

      # @questionnaire.updated_questionnaire(@unique_ident)
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :a_string, :some_text, :a_decimal, :an_integer, :a_date,
                                     :a_time, :file)
    end
  end

end

app/controllers/aflier_survey/application_controller.rb
module AflierSurvey
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    layout 'questionnaire'
  end
end

app/controllers/aflier_survey/belonging_sections_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class BelongingSectionsController < ApplicationController
    before_action :set_belonging_section, only: [:up, :destroy]

    def up
      @previous_belonging_section = @belonging_section.questionnaire.belonging_sections.find_by(position: @belonging_section.position - 1)
      @previous_belonging_section.update_attribute(:position, @belonging_section.position)
      @belonging_section.update_attribute(:position, @belonging_section.position - 1)

      redirect_to edit_questionnaire_path(@belonging_section.questionnaire)
    end

    def destroy
      @questionnaire = @belonging_section.questionnaire
      @belonging_section.destroy

      redirect_to edit_questionnaire_path(@questionnaire)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_belonging_section
      @belonging_section = BelongingSection.find(params[:id])
    end
  end

end

app/controllers/aflier_survey/calc_inputs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcInputsController < ApplicationController
    before_action :set_calc_input, only: [:show, :edit, :update, :destroy]

    # GET /calc_inputs
    def index
      @calc_inputs = CalcInput.all
    end

    # GET /calc_inputs/1
    def show
    end

    # GET /calc_inputs/new
    def new
      @calc_input = CalcInput.new
    end

    # GET /calc_inputs/1/edit
    def edit
    end

    # POST /calc_inputs
    def create
      @calc_input = CalcInput.new(calc_input_params)

      if @calc_input.save
        redirect_to @calc_input, notice: 'Calc input was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /calc_inputs/1
    def update
      if @calc_input.update(calc_input_params)
        redirect_to @calc_input, notice: 'Calc input was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /calc_inputs/1
    def destroy
      @calc_input.destroy
      redirect_to calc_inputs_url, notice: 'Calc input was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_calc_input
        @calc_input = CalcInput.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def calc_input_params
        params.require(:calc_input).permit(:calc_id, :calc_input_id)
      end
  end
end

app/controllers/aflier_survey/calcs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcsController < ApplicationController
    before_action :set_calc, only: [:show, :edit, :update, :destroy, :var_one, :var_two, :operator, :calc_one,
                                    :calc_two, :choice, :grouping, :question_choice]

    # GET /calcs
    # GET /calcs.json
    def index
      @calcs = Calc.all.order(:name)
      @calc = Calc.new
    end

    # GET /calcs/1
    # GET /calcs/1.json
    def show
      if @calc.operation == Calc::ADD
        if @calc.calc_first
          @calc.calc_inputs.create(calc_input_id: @calc.first_calc_id)
          @calc.update_attribute(:first_calc_id, nil)
        end

        if @calc.calc_second
          @calc.calc_inputs.create(calc_input_id: @calc.second_calc_id)
          @calc.update_attribute(:second_calc_id, nil)
        end

        if @calc.question_first
          @calc.question_inputs.create(question_id: @calc.first_question_id)
          @calc.update_attribute(:first_question_id, nil)
        end

        if @calc.question_second
          @calc.question_inputs.create(question_id: @calc.second_question_id)
          @calc.update_attribute(:second_question_id, nil)
        end
      end
    end

    # GET /calcs/new
    def new
      @calc = Calc.new
    end

    # GET /calcs/1/edit
    def edit
    end

    # POST /calcs
    # POST /calcs.json
    def create
      @calc = Calc.new(calc_params)

      respond_to do |format|
        if @calc.save!
          format.html { redirect_to @calc, notice: 'Calc was successfully created.' }
          format.json { render :show, status: :created, location: @calc }
        else
          format.html { render :new }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /calcs/1
    # PATCH/PUT /calcs/1.json
    def update
      respond_to do |format|
        if @calc.update(calc_params)
          format.html { redirect_to @calc, notice: 'Calc was successfully updated.' }
          format.json { render :show, status: :ok, location: @calc }
        else
          format.html { render :edit }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /calcs/1
    # DELETE /calcs/1.json
    def destroy
      @calc.destroy
      respond_to do |format|
        format.html { redirect_to calcs_url, notice: 'Calc was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def var_one
      if @calc.operation == Calc::ADD or
          @calc.operation == Calc::CHOICE or
          @calc.operation == Calc::LOWEST

        existing_calc = @calc.question_inputs.find_by(question_id: params[:question_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.question_inputs.find_or_create_by!(question_id: params[:question_id])
        end
      else
        @calc.update_attributes(first_question_id: params[:question_id], first_calc_id: nil)
      end

      redirect_to @calc
    end

    def var_two
      @calc.update_attributes(second_question_id: params[:question_id], second_calc_id: nil)

      redirect_to @calc
    end

    def calc_one
      if @calc.operation == Calc::ADD or @calc.operation == Calc::CHOICE
        existing_calc = @calc.calc_inputs.find_by(calc_input_id: params[:calc_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.calc_inputs.find_or_create_by(calc_input_id: params[:calc_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def grouping
      if @calc.operation == Calc::COLLECTION
        result_grouping = @calc.grouping_inputs.find_by(result_grouping_id: params[:result_grouping_id])

        if result_grouping
          result_grouping.destroy
        else
          @calc.grouping_inputs.find_or_create_by(result_grouping_id: params[:result_grouping_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def calc_two
      @calc.update_attributes(second_calc_id: params[:calc_id], second_question_id: nil)

      redirect_to @calc
    end

    def operator
      @calc.update_attribute(:operation, params[:operator])
      redirect_to @calc
    end

    def choice
      @calc_choice = @calc.calc_choices.find_or_create_by!(option_id: params[:option_id])
      @calc_choice.update_attributes(calc_result_id: params[:calc_result_id])

      redirect_to @calc
    end

    def question_choice
      @question_choice = @calc.question_choices.find_or_create_by!(option_id: params[:option_id])
      @question_choice.update_attributes(question_id: params[:question_id])

      redirect_to @calc
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_calc
      @calc = Calc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calc_params
      params.require(:calc).permit(:name, :first_question_id, :second_question_id, :operation, :a_decimal,
                                   :treat_repeat)
    end
  end
end

app/views/aflier_survey/questions/_bar.html.erb
<canvas id="myChart" style="max-width:500px; margin: 0 auto;"></canvas>

<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myRadarChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [
                <% question.calc.result_groupings.each do |result_grouping| %>
                '<%= result_grouping.name %>',
                <% end %>
            ],
            datasets: [{
                data: [
                    <% question.calc.result_groupings.each do |result_grouping| %>
                    '<%= result_grouping.percentage(answer.user) %>',
                    <% end %>
                ],
                backgroundColor: [
                    "rgba(255, 99, 132, 0.2)",
                    "rgba(255, 159, 64, 0.2)",
                    "rgba(255, 205, 86, 0.2)",
                    "rgba(75, 192, 192, 0.2)",
                    "rgba(54, 162, 235, 0.2)",
                    "rgba(153, 102, 255, 0.2)",
                    "rgba(201, 203, 207, 0.2)"],
                borderColor: [
                    "rgb(255, 99, 132)",
                    "rgb(255, 159, 64)",
                    "rgb(255, 205, 86)",
                    "rgb(75, 192, 192)",
                    "rgb(54, 162, 235)",
                    "rgb(153, 102, 255)",
                    "rgb(201, 203, 207)"],
                borderWidth: 1
            }]
        },
        options: {
            legend: {
                display: false
            },
            tooltips: {
                callbacks: {
                    label: function(tooltipItem) {
                        return tooltipItem.yLabel;
                    }
                }
            },
            color: [
                'red'
            ],
            scales: {
                axes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            }
        }
    });
</script>

app/views/aflier_survey/questions/_default_edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="btn-group-vertical btn-block">
      <%= render 'questions_list' %>
    </div>

  </div>
  <div class="col">
    <% if @question.question_type == AflierSurvey::Question::CALCULATION or @question.question_type == AflierSurvey::Question::CALCULATION_LONG or @question.question_type == AflierSurvey::Question::RESULT %>
      <div class="row">
        <div class="col-md-6">
          <% if @question.question_type == AflierSurvey::Question::RESULT %>
            <% AflierSurvey::Question::RESULT_TYPES.each do |result_type| %>
              <%= link_to result_question_path(@question, result_type: result_type), class: "btn" do %>
                <%= icons__radio(@question.result_type == result_type, result_type.capitalize) %>
              <% end %>
            <% end %>
          <% end %>

          <h2>Calculations</h2>

          <% AflierSurvey::Calc.all.order(:name).each do |calc| %>
            <%= link_to raw('<i class="fas fa-chevron-circle-right"></i>'), calc %>
            <% if @question.calc_id == calc.id %>
              <%= link_to raw('<i class="fas fa-toggle-on"></i> ' + calc.name), calc_question_path(@question, calc_id: calc.id) %><br>
            <% else %>
              <%= link_to raw('<i class="fas fa-toggle-off"></i> ' + calc.name), calc_question_path(@question, calc_id: calc.id) %><br>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-6">
          <h3>Values from Answers</h3>

          <% AflierSurvey::QuestionSection.all.order(:name).each do |question_section| %>
            <div class="btn btn-outline-primary btn-block" data-toggle="collapse" data-target="#section-<%= question_section.id %>" aria-expanded="false" aria-controls="collapseExample">
              <%= question_section.name %>
            </div>

            <div id="section-<%= question_section.id %>" class="collapse <%= 'show' if question_section.questions.find_by(id: @question.question_id) or question_section.questions.find_by(id: @question.question_y_id) %>">
              <div id="" class="card">
                <% unless question_section.questions.where(question_type: AflierSurvey::Question::CALCULATION_TYPE).empty? %>
                  <ul class="list-group list-group-flush">
                    <% question_section.questions.where(question_type: AflierSurvey::Question::CALCULATION_TYPE).order(:position).each do |question| %>
                      <li class="list-group-item">
                        <%= link_to question.name, feed_question_path(@question, question_id: question.id), class: "btn #{ (@question.question_id == question.id or @question.question_y_id == question.id) ? 'btn-primary' : 'btn-outline-secondary' } btn-block" %>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <% if @question.result_type == AflierSurvey::Question::TABLE %>
        <%= render 'table_weighting' %>
      <% else %>
        <%= render 'question_weighting' if false %>
      <% end %>

    <% elsif @question.links_to_section? %>
      <h2><%= @question.question_section.name %></h2>
      <%= render 'question_weighting' if false%>

    <% elsif @question.weighting_on_value_given and false %>
      <%= render 'question_weighting' %>

    <% elsif @question.question_type == AflierSurvey::Question::OUT_OF %>
      <div class="card shadow mb-3">
        <div class="card-header">Range</div>
        <div class="card-body">
          <div class="mb-3">
            <label>Minimum</label>
            <%= render 'stimulus/edit_in_place/general_input',
                       field_type: :integer,
                       klass: @question,
                       attribute: :minimum,
                       options: { url: aflier_survey.question_path(@question),
                                  value: @question.minimum} %>
          </div>

          <label>Maximum</label>
          <%= render 'stimulus/edit_in_place/general_input',
                     field_type: :integer,
                     klass: @question,
                     attribute: :maximum,
                     options: { url: aflier_survey.question_path(@question),
                                value: @question.maximum} %>

        </div>
      </div>
    <% elsif @question.question_type == AflierSurvey::Question::SELECT_ONE or @question.question_type == AflierSurvey::Question::SELECT_MANY %>
      <h2>Question options</h2>

      <table class="table">
        <thead>
        <tr>
          <th>Option</th>
          <th>value</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @options.each do |option| %>
          <tr>
            <td><%= option.name %></td>
            <td><%= option.a_decimal %></td>
            <td>
              <div class="float-right btn-group">
                <%= link_to raw('<i class="fa fa-arrow-up" aria-hidden="true"></i>'), aflier_survey.up_option_path(option), class: "btn btn-outline-secondary btn-sm" unless option.position == 0 %>
                <%= link_to 'Edit', edit_option_path(option), class: "btn btn-outline-secondary btn-sm" %>
                <%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
              </div>
            </td>
          </tr>
        <% end %>
        <tr>
          <% if @question.text_on_other %>
            <td>Other</td>
            <td></td>
            <td>
              <div class="float-right">
                <%= link_to 'Remove "Other"', toggle_other_question_path(@question), class: "btn btn-outline-warning btn-sm" if @question.text_on_other %>
              </div>
            </td>
          <% end %>
        </tr>
        <tr>
          <td colspan="2"></td>
          <td>
            <div class="float-right">
              <%= link_to 'Add "Other"', toggle_other_question_path(@question), class: "btn btn-outline-primary btn-sm" unless @question.text_on_other %>
              <%= render 'aflier_survey/options/form' %>
            </div>
          </td>
        </tr>
        </tbody>
      </table>

      <%= render 'option_weighting' if false %>
    <% end %>
  </div>

  <div class="col-md-3">
    <div class="card shadow mb-3">
      <div class="card-header">Details</div>
      <div class="card-body">
        <label>Key</label>

        <%= render 'stimulus/edit_in_place/general_input',
                   field_type: nil,
                   klass: @question,
                   attribute: :unique_key,
                   options: { url: aflier_survey.question_path(@question),
                              value: @question.unique_key} %>

        <%= render 'stimulus/edit_in_place/toggle_input',
                   path_on: toggle_input_question_path(@question, attribute: 'required', value: true),
                   path_off: toggle_input_question_path(@question, attribute: 'required', value: false),
                   value: @question.required, choice: 'Required' %>


        <ul class="list-group list-group-flush">
          <% if @question.question_type == AflierSurvey::Question::CALCULATION_LONG %>
            <li class="list-group-item">
              <h4>Value when true:</h4>
              <%= @question.result_grouping&.name %>
            </li>
          <% end %>
          <% if @question.question_type == AflierSurvey::Question::YES_OR_NO %>
            <li class="list-group-item">
              <h4>Value when true:</h4>
              <%= @question.value_true %>
            </li>
            <li class="list-group-item">
              <h4>Value when false:</h4>
              <%= @question.value_false %>
            </li>
          <% end %>
          <% if @question.result_type == AflierSurvey::Question::TABLE %>
            <li class="list-group-item">
              <h4>Bounds (x):</h4>
              <%= @question.bounds_x %>
            </li>
            <li class="list-group-item">
              <h4>Bounds (y):</h4>
              <%= @question.bounds_y %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="card-footer">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editQuestion">
          Edit Question
        </button>
        <% if @question.question_type == AflierSurvey::Question::SELECT_ONE or @question.question_type == AflierSurvey::Question::SELECT_MANY %>
          <%= link_to "Clone", clone_question_path(@question), class: "btn btn-outline-secondary" %>
        <% end %>
      </div>
    </div>

    <!-- Modal -->
    <%= simple_form_for(@question) do |f| %>
      <div class="modal fade" id="editQuestion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Question</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= f.input :name %>
              <%= f.input :text_hint, hint: "Extra hint text to be placed after the question name" %>
              <%= f.input :allow_not_sure %>
              <%= f.input :help %>
              <%= f.input :required %>

              <% if @question.question_type == AflierSurvey::Question::YES_OR_NO %>
                <%= f.input :value_true %>
                <%= f.input :value_false %>
              <% end %>

              <% if @question.result_type == AflierSurvey::Question::TABLE %>
                <%= f.input :bounds_x %>
                <%= f.input :bounds_y %>
              <% end %>

              <%= f.association :question_section, include_blank: false %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
              <%= f.button :submit, class: "btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/aflier_survey/questions/edit.html.erb
<h1><%= @question.name %></h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to 'All Sections', question_sections_path %></li>
  <li class="breadcrumb-item"><%= link_to @question.question_section.name, edit_question_section_path(@question.question_section) %></li>
  <li class="breadcrumb-item active"><%= @question.name %></li>
</ol>


<% if @question.question_type == AflierSurvey::Question::RESULT %>
  <%= render 'result_edit' %>
<% else %>
  <%= render 'default_edit' %>
<% end %>

app/views/aflier_survey/questions/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Questions</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<table class="table">
		  <thead>
		    <tr>
          <th>Name</th>
          <th>Question type</th>
          <th>Question section</th>
          <th></th>
		    </tr>
		  </thead>
		
		  <tbody>
		    <% @questions.each do |question| %>
		      <tr>
            <td><%= question.name %></td>
            <td><%= question.question_type %></td>
            <td><%= question.question_section&.name %></td>
            <td>
		        	<div class="float-right btn-group">
			        	<%= link_to 'Show', question, class: "btn btn-secondary btn-sm" %>
			        	<%= link_to 'Edit', edit_question_path(question), class: "btn btn-secondary btn-sm" %>
			        	<%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
							</div>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="col-md-3">
		<%= render 'form' %>
	</div>
</div>