config/routes.rb
AflierSurvey::Engine.routes.draw do


  devise_for :users, class_name: "User"

  resources :answers do
    member do
      get :choice
      get :option_choice
      get :other
    end
  end

  resources :choice_answers
  resources :option_answers
  resources :questionnaire_submissions
  resources :repeat_sections
  resources :section_progresses

  resources :question_inputs do
    member do
      get :toggle_subtract
    end
  end

  resources :calc_inputs

  resources :belonging_sections do
    member do
      get :up
    end
  end

  resources :options do
    member do
      get :up
    end
  end


  resources :questions do
    resources :options

    member do
      get :up
      get :down
      get :toggle_other
      get :type
      get :result
      get :following
      get :calc
      get :clone
      get :feed
      get :grouping
      get :toggle_input
    end
  end

  resources :calcs do
    member do
      get :var_one
      get :var_two
      get :calc_one
      get :calc_two
      get :operator
      get :choice
      get :question_choice
      get :grouping
    end
  end

  resources :question_sections do
    resources :questions

    member do
      get :report
      get :repeat
      get :complete
      get :include
      get :exclude
    end
  end

  resources :questionnaires do
    member do
      get :submit
      get :assign
      get :save
      get :toggle_input
    end
  end
end

app/models/aflier_survey/application_record.rb
module AflierSurvey
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/aflier_survey/belonging_section.rb
module AflierSurvey
  class BelongingSection < ApplicationRecord
    belongs_to :questionnaire
    belongs_to :question_section
  end
end

app/models/aflier_survey/calc_input.rb
module AflierSurvey
  class CalcInput < ApplicationRecord
  end
end

app/models/aflier_survey/option.rb
module AflierSurvey
  class Option < ApplicationRecord
    belongs_to :question

    has_many :option_mappings
    has_many :option_answers
  end
end

app/models/aflier_survey/option_answer.rb
module AflierSurvey
  class OptionAnswer < ApplicationRecord
    belongs_to :answer
  end
end

app/models/aflier_survey/question_input.rb
module AflierSurvey
  class QuestionInput < ApplicationRecord
    belongs_to :calc
    belongs_to :question
  end
end

app/models/aflier_survey/questionnaire_submission.rb
module AflierSurvey
  class QuestionnaireSubmission < ApplicationRecord
    belongs_to :questionnaire

    validates :unique_ident, presence: true

    SAVED      = 'saved'
    SUBMITTED  = 'submitted'
    UPDATED    = 'updated'
    LOOKING_AT = 'looking_at'
    ASSIGNED   = 'assigned'
  end

end

app/models/aflier_survey/section_progress.rb
module AflierSurvey
  class SectionProgress < ApplicationRecord
    belongs_to :question_section

    COMPLETE = 'complete'.freeze
    UPDATED = 'updated'.freeze
    REQUIRED = 'required'.freeze
  end
end

app/controllers/aflier_survey/answers_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class AnswersController < ApplicationController
    before_action :set_answer, only: [:show, :edit, :update, :destroy, :choice, :option_choice, :other]

    skip_before_action :verify_authenticity_token

    # GET /answers
    # GET /answers.json
    def index
      @answers = Answer.all
    end

    # GET /answers/1
    # GET /answers/1.json
    def show
    end

    # GET /answers/new
    def new
      @answer = Answer.new
    end

    # GET /answers/1/edit
    def edit
    end

    # POST /answers
    # POST /answers.json
    def create
      @answer = Answer.create!(answer_params)

      if @next_question.nil?
        redirect_to @answer.question.question_section
      else
        redirect_to @next_question
      end
    end

    # PATCH/PUT /answers/1
    # PATCH/PUT /answers/1.json
    def update
      # @questionnaire = Questionnaire.find(params[:answer][:questionnaire_id])

      @unique_ident = @answer.unique_ident
      @answer.update!(answer_params)
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @answer.question.question_section
      @many = @question_section.many

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        # format.html { redirect_to question_section_path(@answer.question.question_section, unique_ident: unique_ident), notice: 'Option was successfully updated.' }

        #        format.html { render 'update.js.erb'}
        format.js
        format.json
      end
    end

    # DELETE /answers/1
    # DELETE /answers/1.json
    def destroy
      @answer.destroy
      respond_to do |format|
        format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @question = @answer.question
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      new_answer = params[:choice]

      @answer.update_on_button_press(new_answer)

      @required_warning = @question.is_required?(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          partial = ''

          if @question.question_type == Question::TEXT_ON_YES
            partial = 'aflier_survey/questions/text_on_yes'
          elsif @question.question_type == Question::YES_OR_NO
            partial = 'aflier_survey/questions/yes_or_no'
          elsif @question.question_type == Question::OUT_OF
            partial = 'aflier_survey/questions/out_of'
          end

          render json: {
            html: render_to_string(partial: partial,
                                   formats: :html,
                                   locals: { locked: false, question: @question, answer: @answer })
          }
        end
      end
    end

    def option_choice
      @admin = false # TODO - Will be taken from call

      # @questionnaire  = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @repeat_section = @answer.repeat_section if @answer.question.question_section.many?

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.option_answers.find_or_create_by!(option_id: params[:option_id], unique_ident: @unique_ident)
        @answer.update_attribute(:other, false)
      else
        @option_answers = @answer.option_answers.where(option_id: params[:option_id])
        if @option_answers.empty?
          @answer.option_answers.create!(option_id: params[:option_id], unique_ident: @unique_ident)
        else
          @option_answers.destroy_all
        end
      end

      @question = @answer.question
      @answer.update(not_sure: false)

      @required_warning = @question.is_required?(@unique_ident)
      # @questionnaire.updated_questionnaire(@unique_ident)

      respond_to do |format|
        format.html
        format.json do
          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end
        end
      end
    end

    def other
      #      @questionnaire    = Questionnaire.find(params[:questionnaire_id])
      @unique_ident = @answer.unique_ident
      @question = @answer.question
      @repeat_section = @answer.repeat_section
      @question_section = @question.question_section

      if @answer.question.question_type == Question::SELECT_ONE
        @answer.option_answers.destroy_all
        @answer.update(other: true)
      else
        @answer.update(other: !@answer.other)
      end

      respond_to do |format|
        format.html
        format.json do

          if @answer.question.question_type == Question::SELECT_ONE
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_one',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          else
            render json: { html: render_to_string(partial: 'aflier_survey/questions/select_many',
                                                  formats: :html,
                                                  locals: { locked: false, question: @question, answer: @answer }) }
          end

        end
      end

      # @questionnaire.updated_questionnaire(@unique_ident)
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :a_string, :some_text, :a_decimal, :an_integer, :a_date,
                                     :a_time, :file)
    end
  end

end

app/controllers/aflier_survey/application_controller.rb
module AflierSurvey
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    layout 'questionnaire'
  end
end

app/controllers/aflier_survey/belonging_sections_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class BelongingSectionsController < ApplicationController
    before_action :set_belonging_section, only: [:up, :destroy]

    def up
      @previous_belonging_section = @belonging_section.questionnaire.belonging_sections.find_by(position: @belonging_section.position - 1)
      @previous_belonging_section.update_attribute(:position, @belonging_section.position)
      @belonging_section.update_attribute(:position, @belonging_section.position - 1)

      redirect_to edit_questionnaire_path(@belonging_section.questionnaire)
    end

    def destroy
      @questionnaire = @belonging_section.questionnaire
      @belonging_section.destroy

      redirect_to edit_questionnaire_path(@questionnaire)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_belonging_section
      @belonging_section = BelongingSection.find(params[:id])
    end
  end

end

app/controllers/aflier_survey/calc_inputs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcInputsController < ApplicationController
    before_action :set_calc_input, only: [:show, :edit, :update, :destroy]

    # GET /calc_inputs
    def index
      @calc_inputs = CalcInput.all
    end

    # GET /calc_inputs/1
    def show
    end

    # GET /calc_inputs/new
    def new
      @calc_input = CalcInput.new
    end

    # GET /calc_inputs/1/edit
    def edit
    end

    # POST /calc_inputs
    def create
      @calc_input = CalcInput.new(calc_input_params)

      if @calc_input.save
        redirect_to @calc_input, notice: 'Calc input was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /calc_inputs/1
    def update
      if @calc_input.update(calc_input_params)
        redirect_to @calc_input, notice: 'Calc input was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /calc_inputs/1
    def destroy
      @calc_input.destroy
      redirect_to calc_inputs_url, notice: 'Calc input was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_calc_input
        @calc_input = CalcInput.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def calc_input_params
        params.require(:calc_input).permit(:calc_id, :calc_input_id)
      end
  end
end

app/controllers/aflier_survey/calcs_controller.rb
require_dependency "aflier_survey/application_controller"

module AflierSurvey
  class CalcsController < ApplicationController
    before_action :set_calc, only: [:show, :edit, :update, :destroy, :var_one, :var_two, :operator, :calc_one,
                                    :calc_two, :choice, :grouping, :question_choice]

    # GET /calcs
    # GET /calcs.json
    def index
      @calcs = Calc.all.order(:name)
      @calc = Calc.new
    end

    # GET /calcs/1
    # GET /calcs/1.json
    def show
      if @calc.operation == Calc::ADD
        if @calc.calc_first
          @calc.calc_inputs.create(calc_input_id: @calc.first_calc_id)
          @calc.update_attribute(:first_calc_id, nil)
        end

        if @calc.calc_second
          @calc.calc_inputs.create(calc_input_id: @calc.second_calc_id)
          @calc.update_attribute(:second_calc_id, nil)
        end

        if @calc.question_first
          @calc.question_inputs.create(question_id: @calc.first_question_id)
          @calc.update_attribute(:first_question_id, nil)
        end

        if @calc.question_second
          @calc.question_inputs.create(question_id: @calc.second_question_id)
          @calc.update_attribute(:second_question_id, nil)
        end
      end
    end

    # GET /calcs/new
    def new
      @calc = Calc.new
    end

    # GET /calcs/1/edit
    def edit
    end

    # POST /calcs
    # POST /calcs.json
    def create
      @calc = Calc.new(calc_params)

      respond_to do |format|
        if @calc.save!
          format.html { redirect_to @calc, notice: 'Calc was successfully created.' }
          format.json { render :show, status: :created, location: @calc }
        else
          format.html { render :new }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /calcs/1
    # PATCH/PUT /calcs/1.json
    def update
      respond_to do |format|
        if @calc.update(calc_params)
          format.html { redirect_to @calc, notice: 'Calc was successfully updated.' }
          format.json { render :show, status: :ok, location: @calc }
        else
          format.html { render :edit }
          format.json { render json: @calc.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /calcs/1
    # DELETE /calcs/1.json
    def destroy
      @calc.destroy
      respond_to do |format|
        format.html { redirect_to calcs_url, notice: 'Calc was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def var_one
      if @calc.operation == Calc::ADD or
          @calc.operation == Calc::CHOICE or
          @calc.operation == Calc::LOWEST

        existing_calc = @calc.question_inputs.find_by(question_id: params[:question_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.question_inputs.find_or_create_by!(question_id: params[:question_id])
        end
      else
        @calc.update_attributes(first_question_id: params[:question_id], first_calc_id: nil)
      end

      redirect_to @calc
    end

    def var_two
      @calc.update_attributes(second_question_id: params[:question_id], second_calc_id: nil)

      redirect_to @calc
    end

    def calc_one
      if @calc.operation == Calc::ADD or @calc.operation == Calc::CHOICE
        existing_calc = @calc.calc_inputs.find_by(calc_input_id: params[:calc_id])

        if existing_calc
          existing_calc.destroy
        else
          @calc.calc_inputs.find_or_create_by(calc_input_id: params[:calc_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def grouping
      if @calc.operation == Calc::COLLECTION
        result_grouping = @calc.grouping_inputs.find_by(result_grouping_id: params[:result_grouping_id])

        if result_grouping
          result_grouping.destroy
        else
          @calc.grouping_inputs.find_or_create_by(result_grouping_id: params[:result_grouping_id])
        end
      else
        @calc.update_attributes(first_calc_id: params[:calc_id], first_question_id: nil)
      end

      redirect_to @calc
    end

    def calc_two
      @calc.update_attributes(second_calc_id: params[:calc_id], second_question_id: nil)

      redirect_to @calc
    end

    def operator
      @calc.update_attribute(:operation, params[:operator])
      redirect_to @calc
    end

    def choice
      @calc_choice = @calc.calc_choices.find_or_create_by!(option_id: params[:option_id])
      @calc_choice.update_attributes(calc_result_id: params[:calc_result_id])

      redirect_to @calc
    end

    def question_choice
      @question_choice = @calc.question_choices.find_or_create_by!(option_id: params[:option_id])
      @question_choice.update_attributes(question_id: params[:question_id])

      redirect_to @calc
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_calc
      @calc = Calc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calc_params
      params.require(:calc).permit(:name, :first_question_id, :second_question_id, :operation, :a_decimal,
                                   :treat_repeat)
    end
  end
end

app/views/aflier_survey/answers/_form.html.erb
<button type="button" class="btn btn-block" data-bs-toggle="modal" data-bs-target="#newanswer">
  New Answer
</button>

<div class="modal fade" id="newanswer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <%= simple_form_for(@answer, :html => { :class => 'form-horizontal' },
        wrapper: :horizontal_form,
        wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
        }) do |f| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Answer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <%= f.association :question %>
            <%= f.association :user %>
            <%= f.input :a_string %>
            <%= f.input :some_text %>
            <%= f.input :a_decimal %>
            <%= f.input :an_integer %>
            <%= f.input :a_date %>
            <%= f.input :a_time %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.button :submit %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/aflier_survey/answers/choice.js.erb
<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', repeat_section: @repeat_section, question: @question, answer: @answer %>');
<% else %>
 $('#question-<%= @question.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', questionnaire: @questionnaire, question: @question, answer: @answer, unique_ident: @unique_ident, admin: @admin, locked: false, show_required: true %>');
  $('#following-section-<%= @question.question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/following_section', questionnaire: @questionnaire, unique_ident: @unique_ident, admin: @admin %>');
<% end %>

<% if false %>
$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', unique_ident: @unique_ident %>');
<% end %>

$('#complete-<%= @question_section.id %>').fadeOut('500');
$('#card-footer-<%= @question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/card_footer', question_section: @question_section, unique_ident: @unique_ident, questionnaire: @questionnaire %>');

app/views/aflier_survey/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/aflier_survey/answers/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Answers</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-9">
		<table class="table">
		  <thead>
		    <tr>
                        <th>Question</th>
                        <th>User</th>
                        <th>A string</th>
                        <th>Some text</th>
                        <th>A decimal</th>
                        <th>An integer</th>
                        <th>A date</th>
                        <th>A time</th>
          		      <th></th>
		    </tr>
		  </thead>
		
		  <tbody>
		    <% @answers.each do |answer| %>
		      <tr>
				        <td><%= answer.question %></td>
				        <td><%= answer.unique_ident %></td>
				        <td><%= answer.a_string %></td>
				        <td><%= answer.some_text %></td>
				        <td><%= answer.a_decimal %></td>
				        <td><%= answer.an_integer %></td>
				        <td><%= answer.a_date %></td>
				        <td><%= answer.a_time %></td>
				        <td>
		        	<div class="pull-right btn-group">
			        	<%= link_to 'Show', answer, class: "btn btn-secondary btn-sm" %>
			        	<%= link_to 'Edit', edit_answer_path(answer), class: "btn btn-secondary btn-sm" %>
			        	<%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
							</div>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="col-md-3">
		<%= render 'form' %>
	</div>
</div>

app/views/aflier_survey/answers/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>New Answer</h1>
		</div>
	</div>
</div>

<%= render 'form' %>

app/views/aflier_survey/answers/option_choice.js.erb
<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', repeat_section: @repeat_section, question: @question, answer: @answer %>');
<% else %>
  $('#question-<%= @question.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', questionnaire: @questionnaire, question: @question, answer: @answer, unique_ident: @unique_ident, admin: @admin, locked: false, show_required: false %>');
<% end %>

<% if false %>
$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', questionnaire: @questionnaire, user: @user, unique_ident: @unique_identm, submitted: false %>');
<% end %>

app/views/aflier_survey/answers/other.js.erb
<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', repeat_section: @repeat_section, question: @question, answer: @answer %>');
<% else %>
  $('#question-<%= @question.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', unique_ident: @unique_ident, questionnaire: @questionnaire, question: @question, answer: @answer, locked: false, show_required: false %>');
<% end %>

<% if false %>
$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', questionnaire: @questionnaire, unique_ident: @unique_ident %>');
<% end %>

$('#complete-<%= @question_section.id %>').fadeOut('500');
$('#card-footer-<%= @question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/card_footer', questionnaire: @questionnaire, question_section: @question_section, user: @user %>');

app/views/aflier_survey/answers/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Answer</h1>
		</div>
		
		<ol class="breadcrumb">
		  <li class="breadcrumb-item"><a href="#">Home</a></li>
		  <li class="breadcrumb-item"><a href="#">Parent</a></li>
		  <li class="active">Answer</li>
		</ol>
	</div>
</div>

<div class="row">
	<div class="col-md-9">

	</div>
	<div class="col-md-3">
		<%= link_to 'Edit', edit_answer_path(@answer), class: "btn btn-default btn-block" %>

		        <p>
          <strong>Question:</strong>
          <%= @answer.question %>
        </p>
		        <p>
          <strong>User:</strong>
          <%= @answer.user %>
        </p>
		        <p>
          <strong>A string:</strong>
          <%= @answer.a_string %>
        </p>
		        <p>
          <strong>Some text:</strong>
          <%= @answer.some_text %>
        </p>
		        <p>
          <strong>A decimal:</strong>
          <%= @answer.a_decimal %>
        </p>
		        <p>
          <strong>An integer:</strong>
          <%= @answer.an_integer %>
        </p>
		        <p>
          <strong>A date:</strong>
          <%= @answer.a_date %>
        </p>
		        <p>
          <strong>A time:</strong>
          <%= @answer.a_time %>
        </p>
			</div>
</div>

app/views/aflier_survey/answers/update.js.erb
// alert('doing it!');

<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', questionnaire: @questionnaire, unique_ident: @unique_ident, repeat_section: @repeat_section, question: @question, answer: @answer, admin: current_user.admin %>');
<% else %>
    <% if @question %>
      // alert('redraw_question');
      $('#question-<%= @question.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', questionnaire: @questionnaire, question: @question, unique_ident: @unique_ident, admin: false %>');
      // alert('redrawn question');
    <% end %>
<% end %>

$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', questionnaire: @questionnaire, user: @user, unique_ident: @unique_ident %>');
$('#complete-<%= @question_section.id %>').fadeOut('500');
$('#card-footer-<%= @question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/card_footer', question_section: @question_section, user: @user, questionnaire: @questionnaire %>');

// alert('done it!');

app/views/aflier_survey/answers/x_choice.js.erb
<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', repeat_section: @repeat_section, question: @question, answer: @answer %>');
<% else %>
 $('#question-<%= @question.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', questionnaire: @questionnaire, question: @question, answer: @answer, unique_ident: @unique_ident, admin: @admin, locked: false, show_required: true %>');
  $('#following-section-<%= @question.question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/following_section', questionnaire: @questionnaire, unique_ident: @unique_ident, admin: @admin %>');
<% end %>

<% if false %>
$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', unique_ident: @unique_ident %>');
<% end %>

$('#complete-<%= @question_section.id %>').fadeOut('500');
$('#card-footer-<%= @question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/card_footer', question_section: @question_section, unique_ident: @unique_ident, questionnaire: @questionnaire %>');

app/views/aflier_survey/answers/x_option_choice.js.erb
<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', repeat_section: @repeat_section, question: @question, answer: @answer %>');
<% else %>
  $('#question-<%= @question.id %>-answer-<%= @answer.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', questionnaire: @questionnaire, question: @question, answer: @answer, unique_ident: @unique_ident, admin: @admin, locked: false, show_required: false %>');
<% end %>

<% if false %>
$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', questionnaire: @questionnaire, user: @user, unique_ident: @unique_identm, submitted: false %>');
<% end %>

app/views/aflier_survey/answers/x_update.js.erb
// alert('doing it!');

<% if @repeat_section %>
  $('#question-<%= @repeat_section.id %>-<%= @question.id %>').replaceWith('<%= j render 'repeat_sections/question', questionnaire: @questionnaire, unique_ident: @unique_ident, repeat_section: @repeat_section, question: @question, answer: @answer, admin: current_user.admin %>');
<% else %>
    <% if @question %>
      // alert('redraw_question');
      $('#question-<%= @question.id %>').replaceWith('<%= j render 'aflier_survey/questions/question', questionnaire: @questionnaire, question: @question, unique_ident: @unique_ident, admin: false %>');
      // alert('redrawn question');
    <% end %>
<% end %>

$('#submissions-bar').replaceWith('<%= j render 'aflier_survey/questionnaires/submission_bar', questionnaire: @questionnaire, user: @user, unique_ident: @unique_ident %>');
$('#complete-<%= @question_section.id %>').fadeOut('500');
$('#card-footer-<%= @question_section.id %>').replaceWith('<%= j render 'aflier_survey/question_sections/card_footer', question_section: @question_section, user: @user, questionnaire: @questionnaire %>');

// alert('done it!');